crud_app/urls.py
from django.urls import path
from crud_app.views import catagory_view,display,updates,deletes,items_view,item_update,items_list,item_delete,details_view
app_name='crud_app'

urlpatterns=[
    #========FOR CATEGORY CREATED BY THE HOTEL_REGISTER======
    path(route='catagory/',view=catagory_view,name='catagory'),
    path(route='display/',view=display,name='display'),
    path(route='updates/<int:pk>/',view=updates,name='updates'),
    path(route='deletes/<int:pk>/',view=deletes,name='deletes'),
    #========FOR ITEMS CREATED ==============================
     path(route='items/',view=items_view,name='items'),
    path(route='items_list/',view=items_list,name='items_list'),
    path(route='item_update/<int:pk>/',view=item_update,name='item_update'),
    path(route='item_delete/<int:pk>/',view=item_delete,name='item_delete'),
    path(route='details_view/<pk>/',view=details_view,name='details_view'),
    # path(route='item_details_view/<pk>/',view=item_details_view,name='item_details_view'),
]

owner_app/urls.py
from django.urls import path
from owner_app.views import owner_register_view,otp_view,change_pass_view,sample_home_view,owner_login_view,sub_login_view,logout_view,items_display_view
app_name='owner_app'

urlpatterns=[
    path(route='owner_register/',view=owner_register_view,name='owner_register'),
    path(route='otp_view/<int:pk>/',view=otp_view,name='otp_view'),
    path(route='change_pass_view/<int:pk>/',view=change_pass_view,name='change_pass_view'),
    path(route='sample_home_view/',view=sample_home_view,name='sample_home_view'),
    path(route='owner_login_view/',view=owner_login_view,name='owner_login_view'),
    path(route='sub_login_view/',view=sub_login_view,name='sub_login_view'),
    path(route='logout/',view=logout_view,name='logout'),
    path(route='items_display_view/<int:pk>/',view=items_display_view,name='items_display_view'),


]

pro18/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from pro18.views import main_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('proapp18/',view=include('proapp18.urls'),name='proapp18'),
    path('crud_app/',view=include('crud_app.urls'),name='crud_app'),
    path('cart_app/',view=include('cart_app.urls'),name='cart_app'),
    path('buy_app/',view=include('buy_app.urls'),name='buy_app'),
    path('owner_app/',view=include('owner_app.urls'),name='owner_app'),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

owner_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class owner_model(User):
    phone = models.PositiveBigIntegerField(unique=True)
    dob = models.DateField(auto_now=False,auto_now_add=False)
    gender = models.CharField(max_length=10,choices=[['Male','Male'],['Female','Female']])
    restarunt_name=models.CharField(max_length=50)
    restarunt_address=models.CharField(max_length=200)
    restarunt_email=models.EmailField(unique=True)
    restarunt_phoneno=models.PositiveBigIntegerField(unique=True)
    restarunt_location=models.CharField(max_length=150,choices=[['punjagutta','punjagutta'],['hitech city','hitech city'],['kphb','kphb']])
    image=models.ImageField()
    time=models.CharField(max_length=50)
    date_of_join=models.DateTimeField(auto_now=True)

owner_app/forms.py
from django import forms
from owner_app.models import  owner_model
from django.contrib.auth.hashers import make_password
import re
from owner_app.validators import clean_Enter_password
class owner_form(forms.ModelForm):
    class Meta:
        model=owner_model
        fields=['username','first_name','last_name','email','phone','gender','dob','restarunt_name','restarunt_address','restarunt_email','restarunt_phoneno','restarunt_location','image','time']
     
    def clean_username(self):
        username = self.cleaned_data['username']
        if not (username[0].isupper()):
            raise forms.ValidationError('Username start with Upper')
        if len(username) < 3:
            raise forms.ValidationError('username min 3 char')
        if len(username) > 15:
            raise forms.ValidationError('username max 15 char')
        return username
    
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(str(phone)) != 10:
            raise forms.ValidationError('check the Phone Number')
        if str(phone)[0] not in '9876':
            raise forms.ValidationError('start with 9,8,7,6')
        return phone
        


class login_form(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        if not (username[0].isupper()):
            raise forms.ValidationError('Username start with Upper')
        if len(username) < 3:
            raise forms.ValidationError('username min 3 char')
        if len(username) > 15:
            raise forms.ValidationError('username max 15 char')
        return username
    
    def clean_password(self):
        pwd = self.cleaned_data['password']
        if len(pwd) < 4:
            raise forms.ValidationError('password min 4 char')
        if len(pwd) > 15:
            raise forms.ValidationError('password max 15 char')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Numeric')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Special char')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 lower case')
        if len(re.findall('[A-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 upper case')
        return pwd



class change_password_form(forms.Form):
    Enter_password=forms.CharField(widget=forms.PasswordInput,validators=[clean_Enter_password])
    Re_Enter_password=forms.CharField(widget=forms.PasswordInput)
        
    def clean_Re_Enter_password(self):
        pwd = self.cleaned_data['Re_Enter_password']
        if len(pwd) < 4:
            raise forms.ValidationError('password min 4 char')
        if len(pwd) > 15:
            raise forms.ValidationError('password max 15 char')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Numeric')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Special char')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 lower case')
        if len(re.findall('[A-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 upper case')
        return pwd

        

owner_app/views.py
from django.shortcuts import render,redirect
from owner_app.forms import owner_form,login_form,change_password_form
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail 
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail 
from django.conf import settings
from django.http import HttpResponse
from django.contrib import messages
import random
from owner_app.models import owner_model
from crud_app.models import category_model,food_model
# from crud_app.views import details_view
# Create your views here.



pk=None
#password and mail sending to
def owner_register_view(request):
    global pk
    pk=request.user.pk
    form = owner_form()
    if request.method == 'POST' and request.FILES:
        form = owner_form(request.POST,request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            print(user)
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            name=form.cleaned_data['username'][0:4]+"$"+str(form.cleaned_data['phone'])[0:4]
            print(name)
            user.password = make_password(name)
            user.is_staff=True
            if user:
                user.save()
                subject = "Welcome to Hostel management"
                msg = f'''Dear {username},
                        Congratulation! 
                        We are provide you Login details.
                        username={username}
                        password={name}
                        We are giving you welcome wishes.
                        Please Login from website and Change the password.
                        '''
                send_mail(subject=subject,message=msg,from_email = settings.EMAIL_HOST_USER, recipient_list=[email,])
            return redirect('/owner_app/owner_login_view/')
    return render(request=request,template_name='owner_register.html',context={'form':form})
#change password views

def owner_login_view(request):
    form=login_form()
    if request.method=="POST":
        form =login_form(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(username = username,password = password)
            if user:
                login(request,user)
                return redirect(f'/owner_app/sample_home_view/')
            else:
                messages.error(request,'you enter the wrong password or username')
    return render(request,'owner_login.html',context={'form':form})
            
otp_confirm=None
def change_pass_view(request,pk):
    global otp_confirm
    form=change_password_form()
    if request.method=='POST':
        res =owner_model.objects.get(id=pk)
        form=change_password_form(request.POST)
        if form.is_valid():
            if form.cleaned_data['Enter_password']==form.cleaned_data['Re_Enter_password']:
                owner_model.objects.filter(id=pk).update(password=make_password(form.cleaned_data['Enter_password']))
                if res:
                    if res.is_staff:
                        otp = random.randint(0000,9999)
                        otp_confirm = otp
                        email = res.email
                        subject = "Welcome to Hotel management"
                        msg =f'''Dear {request.user},
                                Congratulation! 
                                We are provide you OTP details.                        
                                OTP CONFIRM : {otp}
                                                '''
                    send_mail(subject=subject,message=msg,from_email = settings.EMAIL_HOST_USER, recipient_list=[email,])
                    login(request, res)  
                    return redirect(f'/owner_app/otp_view/{pk}')
    return render(request=request,template_name='ownerchange_password.html',context={'form':form})


def otp_view(request,pk):
    if request.method == 'POST':
        if str(otp_confirm) == str(request.POST['otp_confirm']):
            messages.success(request,'Password change is success')
            return redirect(f'/owner_app/owner_login_view/')
        else:
            logout(request)
            messages.success(request,"otp entered is incorrect")
            return redirect(f'/owner_app/sub_login_view/')
    return render(request=request, template_name='owner_otp.html')

@login_required(login_url='/owner_app/owner_login_view/')
def sample_home_view(request):
    res=category_model.objects.filter(hotel_id=request.user.id)
    return render(request,'sample.html',context={'res':res})

def sub_login_view(request):
    form=login_form()
    if request.method=="POST":
        form =login_form(request.POST)
        if form.is_valid():
            user=owner_model.objects.filter(id=pk)
            print(user)
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            print(username)
            print(password)
            user=authenticate(username = username,password = password)
            if user:
                login(request,user)
                return redirect(f'/owner_app/change_pass_view/{pk}/')
            else:
                messages.error(request,'you enter the wrong password or username')
    return render(request,'sub_login.html',context={'form':form})



@login_required(login_url='/owner_app/owner_login_view/')
def logout_view(request):
    logout(request)
    return redirect('/owner_app/owner_login_view/')

@login_required(login_url='/owner_app/owner_login_view/')
def items_display_view(request,pk):
    res=food_model.objects.filter(category_id=pk)
    return render(request=request,template_name='items_display.html',context={'res':res})

owner_app/templates/items_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
            body {
    font-family: 'Arial', sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f5f5f5; /* Light gray background color */
}

#items-dis {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    padding: 20px;
}

#item {
    background-color: #fff; /* White background for each item */
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Box shadow for a subtle lift effect */
    margin: 15px;
    padding: 20px;
    width: 300px;
}

h4 {
    color: #333; /* Dark gray text color for item name and price */
}

img {
    max-width: 100%;
    height: auto;
    margin-bottom: 15px;
}

p {
    color: #555; /* Slightly lighter gray text color for item description */
}

button {
    background-color: #007BFF; /* Blue button color */
    color: #fff;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    margin-top: 10px;
    transition: background-color 0.3s;
}
#buttons{
    text-align: center;
}

button:hover {
    background-color: #0056b3; /* Darker blue on hover */
}

a {
    text-decoration: none;
}

@media (max-width: 768px) {
    #items-dis {
        padding: 10px;
    }

    #item {
        width: 100%; /* Full width on small screens */
    }
}

    </style>
</head>
<body>
    
    {% include 'partials/_header_owner.html' %}
    <div id="items-dis">
    {% if res%}
        {% for i in res %}
        <div id="item">
        <h4>{{i.item_name}}</h4>
        <h4>{{i.item_price}}</h4>
        <img src="{{i.item_image.url}}" alt="" height="100px" width="100px">
        <p>{{i.item_desc}}</p>
        <a href="{% url 'crud_app:item_update' pk=i.item_id%}"><button>update</button></a>
        <a href="{% url 'crud_app:item_delete' pk=i.item_id%}"><button>delete</button></a>
        </div>
        {% endfor %}
    {% endif %}
</div>
<div id="buttons">
<a href="{% url 'crud_app:items' %}"><button>
    items_create
</button></a>
<a href="{% url 'owner_app:sample_home_view' %}"><button>
    Home
</button></a>
</div>
{% include 'partials/_footer.html' %}
</body>
</html>

owner_app/templates/owner_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>Login_page</title>
    {% load static %}
    <style>
        body{
            display: flex;
            text-align: center;
            width: 50%;
            margin: auto;
            line-height: 180%;
            margin-top:10%;
            background: #43C6AC;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #F8FFAE, #43C6AC);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #F8FFAE, #43C6AC); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

        }
        #body{
            font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            border: 1px solid #43C6AC;
            border-radius: 5px;
            box-shadow: inset 0 0 30px #f8a100;
            padding: 10%;
        }
    </style>
</head>
<body>
    {%if messages %}
    {% for i in messages %}
    <h5>{{i}}</h5>
    {% endfor %}
    {% endif %}
    <div id="body">
    <form action="" method="post" id="form">
        {% csrf_token %}
        <table>
            {{form}}
        </table>
        <input type="submit" value="login">
    </form>
    <a href="{% url 'owner_app:sub_login_view'%}"><button>change password</button></a>
    <h3>New User ? <a href="{% url 'owner_app:owner_register' %}"><button>Register</button></a></h3>
    </div>
</body>
</html>

owner_app/templates/owner_otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>OTP_PAGE</title>
    <style>
    body {
    margin: 0;
    padding: 0;
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    filter: brightness(80%);
    color: #110e0e;
    font-family: 'Arial', sans-serif;
}

.container {
    background-color: rgba(0, 0, 0, 0.7);
    padding: 20px;
    border-radius: 10px;
    text-align: center;
}

h1 {
    font-size: 2em;
    margin-bottom: 20px;
}

label {
    display: block;
    margin-bottom: 10px;
}

input[type="text"] {
    width: 100%;
    padding: 10px;
    box-sizing: border-box;
    margin-bottom: 10px;
}

input[type="submit"] {
    background-color: #007BFF;
    color: #0b0909;
    padding: 10px 20px;
    border: none;
}

    </style>
</head>
<body>
    <h1>OTP Confirm</h1>
    <fieldset>
    <form action="" method="post" class="container">
        {% csrf_token %}
        <label for="id_otp">Enter OTP</label>
        <input type="text" name="otp_confirm" id="id_otp"><br>
        <input type="submit" value="OTP SUBMIT">
    </form>
</fieldset>
</body>
</html>

owner_app/templates/owner_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>owner_register</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/owner_register.css' %}">
    <style>
   body {
    font-family: 'Arial', sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f5f5f5;
}

div {
    max-width: 600px;
    margin: 50px auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    transition: box-shadow 0.3s;
}

h1 {
    text-align: center;
    color: #007BFF;
    transition: color 0.3s;
}

form {
    margin-top: 20px;
}

table {
    width: 100%;
}

input[type="text"],
input[type="password"],
input[type="email"] {
    width: 100%;
    padding: 10px;
    margin: 5px 0;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    transition: border-color 0.3s;
}

input[type="text"]:focus,
input[type="password"]:focus,
input[type="email"]:focus {
    border-color: #007BFF;
}

input[type="submit"] {
    background-color: #007BFF;
    color: #fff;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s;
}

input[type="submit"]:hover {
    background-color: #0056b3;
}

#login {
    text-align: center;
    margin-top: 20px;
}

button {
    background-color: #007BFF;
    color: #fff;
    padding: 8px 12px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s;
}

button:hover {
    background-color: #0056b3;
}

@media (max-width: 768px) {
    div {
        padding: 10px;
    }
}


    </style>
</head>
<body>
    {%if messages %}
    {% for i in messages %}
    <h5>{{i}}</h5>
    {% endfor %}
    {% endif %}
    <div>
        <h1 id="h1-r">Please Register Here</h1>
    <fieldset>
    <form action="" method="post" enctype="multipart/form-data" id="form">
        {% csrf_token %}
    <table>
        {{form.as_p}}
    </table>
    <input type="submit" value="Register">
    </form>
</fieldset>
    
    <div id="login">
        <h3>if your already register login!!!</h3><a href="{% url 'owner_app:owner_login_view' %}"><button>
            login</button></a>
        </div>
        {% include 'partials/_footer.html' %}
</div>
</div>
</body>
</html>

owner_app/templates/ownerchange_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>owner change password</title>
    <style>
        /* Basic styling for the form container */
        div {
            margin-bottom: 15px;
            background-color: #f5f5f5;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 15px;
        }

        /* Style for labels */
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        /* Style for text input and password input fields */
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            transition: border-color 0.3s;
        }

        /* Add transitions for a smoother user experience */
        input[type="text"]:focus,
        input[type="password"]:focus {
            border-color: #007BFF;
        }

        /* Styling for the submit button */
        input[type="submit"] {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s, transform 0.2s,      box-shadow 0.3s;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
            transform: scale(1.05);
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
        }
        fieldset{
            width: 50%;
            margin: 10% auto;
            border-radius: 2%;
  box-shadow: -1px 3px 23px 6px rgba(0, 0, 0, 0.3);
}
        
body{
    background-image: url("{% static 'images/changepass1.jpg' %}");
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
   
}
h3{
    text-align: center;
}
    </style>
</head>
<body>
    
    
   
    <fieldset>
        <h3>You have to change the password to login</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {%  csrf_token %}
            {{form}}
        <input type="submit" value="click here to continue login">
    </form>
</fieldset>
</body>
</html>

owner_app/templates/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <style>
    body {
    font-family: 'Arial', sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f5f5f5; /* Light gray background color */
    text-align: center;
}

#c-display {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    padding: 20px;
}

#main {
    background-color: #fff; /* White background for each item */
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Box shadow for a subtle lift effect */
    margin: 15px;
    padding: 20px;
    width: 300px;
}

h4 {
    color: #333; /* Dark gray text color for category name */
}

img {
    max-width: 100%;
    height: auto;
    margin-bottom: 15px;
}

p {
    color: #555; /* Slightly lighter gray text color for category description */
}

button {
    background-color: #007BFF; /* Blue button color */
    color: #fff;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    margin-top: 10px;
    transition: background-color 0.3s;
}

button:hover {
    background-color: #0056b3; /* Darker blue on hover */
}

@media (max-width: 600px) {
    #main {
        width: 100%; /* Full width on small screens */
    }
}

    
</style>
</head>
<body>
    {% include 'partials/_header_owner.html'%}
    <div id="c-display">
        {% if res %}
            {% for i in res %}
            <div id="main">
                <h4>{{i.category_name}}</h4>
                <a href="{% url 'owner_app:items_display_view' pk=i.category_id %}"><img src="{{i.category_image.url }}" alt="sorry" height="100px" width="100px"></a>
                <p>{{i.category_desc}}</p>
                <a href="{% url 'crud_app:updates' pk=i.category_id %}"><button>update</button></a>
                <a href="{% url 'crud_app:deletes' pk=i.category_id %}"><button>Delete</button></a>
                <a href="{% url 'crud_app:items' %}"><button>Items_create</button></a>
            </div>
            {% endfor %} 
        {% endif%}
    </div>

    {% include 'partials/_footer.html' %}
</body>
</html>

owner_app/templates/sub_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login_page</title>
    {% load static %}
    <style>
        *{
            margin: 0%;
            padding: 0%;
        }
/* Basic styling for the form container */
div {
    margin-bottom: 15px;
}

/* Style for labels */
label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
    color: #fff;
}

/* Style for text input and password input fields */
input[type="text"],
input[type="password"] {
    width: 100%;
    padding: 8px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    transition: border-color 0.3s;
}

/* Add transitions for a smoother user experience */
input[type="text"]:focus,
input[type="password"]:focus {
    border-color: #007BFF;
}

/* Styling for the submit button */
input[type="submit"] {
    background-color: #007BFF;
    color: #fff;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s, transform 0.2s, box-shadow 0.3s;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Add box shadow */
}

input[type="submit"]:hover {
    background-color: #22272c;
    transform: scale(1.05);
    box-shadow: 5px 6px 8px rgba(0, 20, 0, 0.2); /* Adjust box shadow on hover */
}

fieldset{
    padding: 3%;
    display: flex;
    justify-content: center;
    align-items: center;
    width: 50%;
    margin:10% auto;
    border-radius: 2%;
	box-shadow: 0 0 15px -2px #444444;
}
body{
    background-image: url("{% static 'images/header.png' %}");
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
}

    </style>
</head>
<body>
    {%if messages %}
    {% for i in messages %}
    <h5>{{i}}</h5>
    {% endfor %}
    {% endif %}
    <div id="sub-log">
    <fieldset>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form}}
        </table>
        <input type="submit" value="login">
    </form>
</fieldset>
</div>
</body>
</html>