buy_app/urls.py
from django.urls import path
from buy_app.views import buy_register,buy_view,order_details_view,order_details
app_name='buy_app'

urlpatterns=[
    path(route='buy_register/<int:total_price>/',view=buy_register,name='buy_register'),
    path(route='buy_view/',view=buy_view,name='buy_view'),
    path(route='order_details/<int:buy_id>/',view=order_details,name='order_details'),
    path(route='order_details/',view=order_details_view,name='order_details')
    
]

cart_app/urls.py
from django.urls import path 
from cart_app.views import cart_register,cart_view,cart_remove

app_name='cart_app'
urlpatterns=[
    path(route='cart_list/<int:pk>/',view=cart_view,name='cart_list'),
    path(route='cart_register/',view=cart_register,name='cart_register'),
    path(route='cart_remove/<int:cart_id>/<int:hotel_id>/',view=cart_remove,name='cart_remove')
]

pro18/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from pro18.views import main_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('proapp18/',view=include('proapp18.urls'),name='proapp18'),
    path('crud_app/',view=include('crud_app.urls'),name='crud_app'),
    path('cart_app/',view=include('cart_app.urls'),name='cart_app'),
    path('buy_app/',view=include('buy_app.urls'),name='buy_app'),
    path('owner_app/',view=include('owner_app.urls'),name='owner_app'),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proapp18/urls.py
from django.urls import path
from proapp18.views import customer_register,login_view,home_view,logout_view,otp_view,start_view,home_view,category_user_view,items_user_view,customer_update_view,forget_password_view,customer_otp_view,change_pass_view
app_name = 'proapp18'

urlpatterns = [
    path(route='',view=start_view,name='start'),
    path(route='register/',view=customer_register,name='register'),
    path(route='customer_update/<int:pk>/',view=customer_update_view,name='customer_update'),
    path(route='customer_forget/',view=forget_password_view,name='customer_forget'),
    path(route='login/',view=login_view,name='login'),
    path(route='otp/',view=otp_view,name='otp'),
    path(route='customer_otp/<int:pk>/',view=customer_otp_view,name='customer_otp'),
    path(route='home/',view=home_view, name='home'),
    path(route='logout/',view=logout_view,name='logout'),
    path(route='hotel1/',view=home_view,name='hotel'),
    path(route='category_user/<int:pk>/',view=category_user_view,name='category_user'),
    path(route='items_user/<int:hotel>/<int:category>/',view=items_user_view,name='items_user'),
    path(route='change_pass/<int:pk>/',view=change_pass_view,name='change_pass'),
  
]

cart_app/models.py
from django.db import models

# Create your models here.


class cart_model(models.Model):
    cart_id=models.AutoField(primary_key=True)
    customer_id=models.PositiveIntegerField()
    hotel_id=models.PositiveIntegerField()
    customer_name=models.CharField(max_length=110)
    your_item_id=models.IntegerField()
    your_item_name=models.CharField(max_length=150)
    price=models.PositiveIntegerField()
    quantity=models.PositiveIntegerField()
    total_price=models.PositiveIntegerField()

cart_app/forms.py
from django import forms

# from crud_app.models import cart_model

cart_app/views.py
from django.shortcuts import render,redirect
from cart_app.models import cart_model
from crud_app.models import food_model
from django.db.models import Sum,Avg,Count
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url='/proapp18/login/')
def cart_register(request):
    if request.method=='POST':
        res=cart_model.objects.create(customer_id=request.POST['customer_id'],your_item_id=request.POST['your_item_id'],your_item_name=request.POST['your_item_name'],price=int(float(request.POST['price'])),quantity=request.POST['quantity'],hotel_id=request.POST['hotel_id'],total_price=int(float(request.POST['price']))*int(request.POST['quantity']))
        messages.success(request,"Item is added in cart")
        hotel=request.POST['hotel_id']
        return redirect(f'/proapp18/category_user/{hotel}/')
    else:
        messages.error(request,"Item is not added in cart")



@login_required(login_url='/proapp18/login/')
def cart_view(request,pk):
    res=cart_model.objects.filter(customer_id=request.user.id,hotel_id=pk)
    prod_data=food_model.objects.all()
    total_price=cart_model.objects.filter(customer_id=request.user.id,hotel_id=pk).aggregate(Sum('total_price'))
    return render(request=request,template_name='cart_list.html',context={'res':res,'prod_data':prod_data,'total_price':total_price['total_price__sum'],'hotel_id':pk})
    
@login_required(login_url='/proapp18/login/')
def cart_remove(request,cart_id,hotel_id):
    cart_model.objects.filter(cart_id=cart_id).delete()
    messages.success(request,"item is removed")
    return redirect(f'/cart_app/cart_list/{hotel_id}/')

cart_app/templates/cart_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load customtags %}
</head>
<body>
    <div>
        {%if messages %}
        {% for i in messages %}
        <h5>{{i}}</h5>
        {% endfor %}
        {% endif %}

        {% if res %}
        <h2>welcome to {{user}}</h2>
        <h3>Your cart</h3>
        <table border="2px">
            <tr>
                <td>item_id</td>
                <td>item_name</td>
                <td>item_price</td>
                <td>item_quantity</td>
                <td>total_price</td>
                <td>Remove</td>
            </tr>

            {% for i in res %}
            <tr>
                <td>{{i.your_item_id}}</td>
                {% for j in prod_data %}
                    {% if j.item_id == i.your_item_id %}
                        <td>{{i.your_item_name}}</td>
                        <td>{{i.price}}</td>
                        <td>{{i.quantity}}</td>
                        <td>{{i.total_price}}</td>
                    {% endif %} 
                {% endfor %}
                <td><a href="{% url 'cart_app:cart_remove' cart_id=i.cart_id  hotel_id=hotel_id %}"><button>Remove</button></a></td>
              
            </tr>
            {% endfor %}
        </table>
        <h1>Total_price: {{total_price}}</h1>
        </div>
        <a href="{% url 'buy_app:buy_register' total_price=total_price %}"><button>Buy now</button></a>
        {% else %}
        <h2>cart is empty</h2>
        
        {% endif %}
        <a href="{% url 'proapp18:category_user' pk=hotel_id %}"><button>Click here to add the items</button></a>
        <a href="{% url 'proapp18:home'%}"><button>Hotel home</button></a>
</body>
</html>