cart_app/urls.py
from django.urls import path 
from cart_app.views import cart_register,cart_view,cart_remove

app_name='cart_app'
urlpatterns=[
    path(route='cart_list/<int:pk>/',view=cart_view,name='cart_list'),
    path(route='cart_register/',view=cart_register,name='cart_register'),
    path(route='cart_remove/<int:cart_id>/<int:hotel_id>/',view=cart_remove,name='cart_remove')
]

owner_app/urls.py
from django.urls import path
from owner_app.views import owner_register_view,otp_view,change_pass_view,sample_home_view,owner_login_view,sub_login_view,logout_view,items_display_view
app_name='owner_app'

urlpatterns=[
    path(route='owner_register/',view=owner_register_view,name='owner_register'),
    path(route='otp_view/<int:pk>/',view=otp_view,name='otp_view'),
    path(route='change_pass_view/<int:pk>/',view=change_pass_view,name='change_pass_view'),
    path(route='sample_home_view/',view=sample_home_view,name='sample_home_view'),
    path(route='owner_login_view/',view=owner_login_view,name='owner_login_view'),
    path(route='sub_login_view/',view=sub_login_view,name='sub_login_view'),
    path(route='logout/',view=logout_view,name='logout'),
    path(route='items_display_view/<int:pk>/',view=items_display_view,name='items_display_view'),


]

pro18/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from pro18.views import main_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('proapp18/',view=include('proapp18.urls'),name='proapp18'),
    path('crud_app/',view=include('crud_app.urls'),name='crud_app'),
    path('cart_app/',view=include('cart_app.urls'),name='cart_app'),
    path('buy_app/',view=include('buy_app.urls'),name='buy_app'),
    path('owner_app/',view=include('owner_app.urls'),name='owner_app'),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proapp18/urls.py
from django.urls import path
from proapp18.views import customer_register,login_view,home_view,logout_view,otp_view,start_view,home_view,category_user_view,items_user_view,customer_update_view,forget_password_view,customer_otp_view,change_pass_view
app_name = 'proapp18'

urlpatterns = [
    path(route='',view=start_view,name='start'),
    path(route='register/',view=customer_register,name='register'),
    path(route='customer_update/<int:pk>/',view=customer_update_view,name='customer_update'),
    path(route='customer_forget/',view=forget_password_view,name='customer_forget'),
    path(route='login/',view=login_view,name='login'),
    path(route='otp/',view=otp_view,name='otp'),
    path(route='customer_otp/<int:pk>/',view=customer_otp_view,name='customer_otp'),
    path(route='home/',view=home_view, name='home'),
    path(route='logout/',view=logout_view,name='logout'),
    path(route='hotel1/',view=home_view,name='hotel'),
    path(route='category_user/<int:pk>/',view=category_user_view,name='category_user'),
    path(route='items_user/<int:hotel>/<int:category>/',view=items_user_view,name='items_user'),
    path(route='change_pass/<int:pk>/',view=change_pass_view,name='change_pass'),
  
]

proapp18/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class customer_model(User):
    phone = models.PositiveBigIntegerField()
    dob = models.DateField(auto_now=False,auto_now_add=False)
    gender = models.CharField(max_length=10,choices=[['Male','Male'],['Female','Female']])


class hotel_register(models.Model):
    id=models.IntegerField(primary_key=True)
    restarunt_name=models.CharField(max_length=50)
    restarunt_address=models.CharField(max_length=200)
    email=models.EmailField(unique=True)
    phoneno=models.PositiveBigIntegerField(unique=True)
    image=models.ImageField()
    time=models.IntegerField()
    def __str__(self):
        return self.restarunt_name

class hotel_rating(models.Model):
    hotel_id=models.IntegerField()
    rating=models.CharField(max_length=2,choices=[['1','1'],['2','2'],['3','3'],['4','4'],['5','5']])
    comments=models.TextField(null=True)

proapp18/forms.py
from django import forms 
from proapp18.models import customer_model
from django.contrib.auth.hashers import make_password
import re
from proapp18.validators import clean_Enter_password

class customer_form(forms.ModelForm):
    repassword = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = customer_model
        fields = ['username','first_name','last_name','email','phone','gender','dob','password']

    def clean_username(self):
        username = self.cleaned_data['username']
        if not (username[0].isupper()):
            raise forms.ValidationError('Username start with Upper')
        if len(username) < 3:
            raise forms.ValidationError('username min 3 char')
        if len(username) > 15:
            raise forms.ValidationError('username max 15 char')
        return username
    
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(str(phone)) != 10:
            raise forms.ValidationError('check the Phone Number')
        if str(phone)[0] not in '9876':
            raise forms.ValidationError('start with 9,8,7,6')
        return phone
    
    def clean_password(self):
        pwd = self.cleaned_data['password']
        if len(pwd) < 4:
            raise forms.ValidationError('password min 4 char')
        if len(pwd) > 15:
            raise forms.ValidationError('password max 15 char')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Numeric')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Special char')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 lower case')
        if len(re.findall('[A-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 upper case')
        return pwd
    
    def clean_repassword(self):
        pwd = self.cleaned_data['repassword']
        if not (pwd[0].isupper()):
            raise forms.ValidationError('Repassword start with upper char')
        if len(pwd) < 4:
            raise forms.ValidationError('password min 4 char')
        if len(pwd) > 15:
            raise forms.ValidationError('password max 15 char')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Numeric')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Special char')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 lower case')
        if self.cleaned_data['password'] != pwd:
            raise forms.ValidationError('password and repassword should be same')
        return pwd
    

    def save(self, commit = True):
        user = super().save(commit=False)
        if self.cleaned_data['password'] == self.cleaned_data['repassword']:
            user.password = make_password(self.cleaned_data['password'])
            print('hello')
            if commit:
                user.save()
            return user

class login_form(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        if not (username[0].isupper()):
            raise forms.ValidationError('Username start with Upper')
        if len(username) < 3:
            raise forms.ValidationError('username min 3 char')
        if len(username) > 15:
            raise forms.ValidationError('username max 15 char')
        return username
    
    def clean_password(self):
        pwd = self.cleaned_data['password']
        if len(pwd) < 4:
            raise forms.ValidationError('password min 4 char')
        if len(pwd) > 15:
            raise forms.ValidationError('password max 15 char')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Numeric')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Special char')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 lower case')
        if len(re.findall('[A-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 upper case')
        return pwd

class customer_update(forms.ModelForm):
    class Meta:
        model=customer_model
        fields = ['username','first_name','last_name','email','phone','gender','dob']


class customer_change_form(forms.Form):
    Enter_password=forms.CharField(widget=forms.PasswordInput,validators=[clean_Enter_password])
    Re_Enter_password=forms.CharField(widget=forms.PasswordInput)
        
    def clean_Re_Enter_password(self):
        pwd = self.cleaned_data['Re_Enter_password']
        if len(pwd) < 4:
            raise forms.ValidationError('password min 4 char')
        if len(pwd) > 15:
            raise forms.ValidationError('password max 15 char')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Numeric')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 Special char')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 lower case')
        if len(re.findall('[A-Z]', pwd)) == 0:
            raise  forms.ValidationError('altest 1 upper case')
        return pwd

proapp18/views.py
from django.shortcuts import render,redirect
from proapp18.forms import customer_form,login_form,customer_update,customer_change_form
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail 
from django.conf import settings
from django.http import HttpResponse
import random
from crud_app.models import category_model,food_model
from owner_app.models import owner_model
from proapp18.models import customer_model
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
# Create your views here.


def start_view(request):
    return render(request,'index.html')


def customer_register(request):
    form = customer_form()
    if request.method == 'POST':
        form = customer_form(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            subject = "Welcome to TCS Company"
            msg = '''Dear Ncs  Employee,
                    Congratulation! 
                    We will provide you work from home job interested candidates send your name address contact details.
                    We are giving you welcome kit at your address by speed post. 
 
                    We think that your experience and skills will be a valuable asset to our company.
                    '''
            send_mail(subject=subject,message=msg,from_email = settings.EMAIL_HOST_USER, recipient_list=[email,])
        return redirect('/proapp18/login/')
    return render(request=request,template_name='register.html',context={'form':form})



def customer_update_view(request,pk):
    res=customer_model.objects.get(id=pk)
    form = customer_update(instance=res)
    if request.method == 'POST':
        res=customer_model.objects.get(id=pk)
        form = customer_update(request.POST,instance=res)
        if form.is_valid:
            form.save()
            return redirect('/proapp18/home/')
        else:
            return HttpResponse('not saved')
    return render(request=request,template_name='profile.html',context={'form':form})


otp_confirm = None
def login_view(request):
    global otp_confirm
    form = login_form()
    if request.method == "POST":
        form = login_form(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user = authenticate(username = username,password=password)
            if user:
                login(request, user)
                otp = random.randint(0000,9999)
                otp_confirm = otp
                print(otp)
                email = user.email
                print(email)
                subject = "Welcome to TCS Company"
                msg =f'''Dear Ncs  Employee,
 
                        Congratulation! 
                        We will provide you work from home job interested candidates send your name address contact details.
                        We are giving you welcome kit at your address by speed post. 
    
                        We think that your experience and skills will be a valuable asset to our company.
                        
                        OTP CONFIRM : {otp}
                        '''
                send_mail(subject=subject,message=msg,from_email = settings.EMAIL_HOST_USER, recipient_list=[email,])
                print('hai')
            return redirect('/proapp18/otp/')
    return render(request=request,template_name='login.html',context={'form':form})


def otp_view(request):
    if request.method == 'POST':
        if str(otp_confirm) == str(request.POST['otp_confirm']):
            return redirect('/proapp18/home')
        else:
            logout(request)
            return redirect('/proapp18/login/')
    return render(request=request, template_name='otp_genrate.html')


@login_required(login_url='/login')
def logout_view(request):
    logout(request)
    return redirect('/proapp18/login')

@login_required(login_url='/login')
def home_view(request):
    res=owner_model.objects.all()
    # data=category_model.objects.all()
    return render(request=request,template_name='Hotel_home.html',context={'data':res})


def category_user_view(request,pk):
    res=category_model.objects.filter(hotel_id=pk)
    return render(request=request,template_name='customer_cate.html',context={'data':res,'hotel_id':pk})


def items_user_view(request,hotel,category):
    res=food_model.objects.filter(hotel_id=hotel,category_id=category)
    return render(request=request,template_name='items_user.html',context={'data':res})


otp_confirm=None
def forget_password_view(request):
    res=customer_model.objects.all().values_list('email')
    print(res)
    global otp_confirm
    if request.method =='POST':
        otp=random.randint(000000,999999)
        otp_confirm=otp
        email=request.POST['email']
        print(request.POST)
        if (email,) in res :
            subject='customer verifivcation code for the password change'
            msg=f'''DEar customer plese enter
                the otp {otp}
                change the password 
                Thank you for your verification'''
            send_mail(subject=subject,message=msg,from_email=settings.EMAIL_HOST_USER,recipient_list=[email,])
            email_id=customer_model.objects.get(email=email)
            return redirect(f'/proapp18/customer_otp/{email_id.id}/')
        else:
            messages.error(request,'otp is incorrect')
    return render(request,'customer_forget.html')


def customer_otp_view(request,pk):
    if request.method == 'POST':
        if str(otp_confirm) == str(request.POST['otp_confirm']):
            return redirect(f'/proapp18/change_pass/{pk}/')
        else:
            logout(request)
            return redirect('/proapp18/customer_forget/')
    return render(request=request, template_name='customer_otp.html')


def change_pass_view(request,pk):
    form=customer_change_form()
    if request.method=='POST':
        form=customer_change_form(request.POST)
        if form.is_valid():
            if form.cleaned_data['Enter_password']==form.cleaned_data['Re_Enter_password']:
                customer_model.objects.filter(id=pk).update(password=make_password(form.cleaned_data['Enter_password']))
                messages.success(request,'password change successful')
                return redirect('/proapp18/login/')
    return render(request=request,template_name='change_password.html',context={'form':form})

proapp18/templates/Hotel_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- {% load static %}
    <link rel="stylesheet" href="{% static 'css/hotel1.css'%}"> -->

  <!-- BELOW GOOGLE FONTS LINK -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lexend:wght@300&display=swap" rel="stylesheet">
    <title>Home_page</title>
</head>
<body>
 {% include 'partials/_header.html' %}
<div id="div1">   
  
  {% if data %}
    {% for i in data%}
    <div id="div-home">
    <h4>{{i.restarunt_name}}</h4>
    <a href="{% url 'proapp18:category_user' pk=i.id %}"><img src="{{i.image.url}}" alt="" height="
    150px" width="150px"></a>
    <h4>{{i.restarunt_address}}</h4>
    <h4>{{i.restarunt_email}}</h4>
    <h4>{{i.time}}</h4>
    <h4>{{i.phone}}</h4>
    </div>
    {% endfor %}
    {% endif %}
  </div>
  
  {% include 'partials/_footer.html' %}
</body>
</html>

proapp18/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>change password</title>
    <style>
       /* Basic styling for the form container */
div {
    margin-bottom: 15px;
    background-color: #f5f5f5;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    padding: 15px;
}

/* Style for labels */
label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
}

/* Style for text input and password input fields */
input[type="text"],
input[type="password"] {
    width: 100%;
    padding: 8px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    transition: border-color 0.3s;
}

/* Add transitions for a smoother user experience */
input[type="text"]:focus,
input[type="password"]:focus {
    border-color: #007BFF;
}

/* Styling for the submit button */
input[type="submit"] {
    background-color: #007BFF;
    color: #fff;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s, transform 0.2s, box-shadow 0.3s;
}

input[type="submit"]:hover {
    background-color: #0056b3;
    transform: scale(1.05);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
}

    </style>
</head>
<body>
    <div>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" name="" value="change">
    </form>
</div>
</body>
</html>

proapp18/templates/customer_cate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>category_for_user</title>
    <!-- BELOW GOOGLE FONTS LINK -->
  
    <style>
        *{
            padding: 0%;
            margin: 0%;
        }
        #cust-category{
            display: flex;
            justify-content: space-evenly;
            margin-top: 5%;
        }
        #cust-items{
            width:40%;
            border: 1px solid;
            margin: 10px;
            -webkit-box-shadow: 0px 1px 8px 4px rgba(0,0,0,0.84); 
box-shadow: 0px 1px 8px 4px rgba(0,0,0,0.84);
        }
    </style>
</head>
<body>
    <div>
 {% include 'partials/_category_header.html' %}
</div>
<div id="cust-category">
    {% if data %}
        {% for i in data %}
        <div id="cust-items">
            <h4>{{i.category_name}}</h4>
            <a href="{% url 'proapp18:items_user' hotel=i.hotel_id  category=i.category_id %}"><img src="{{i.category_image.url}}" alt="" height="150px" width="150px"></a>
            <p>{{i.category_desc}}</p>
        </div>
        {% endfor %}
    {% endif %}
</div>
<a href="{% url 'proapp18:home'%}"><button>Hotel home</button></a>
{% include 'partials/_footer.html' %}
</body>
</html>

proapp18/templates/customer_forget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <label for="id_email">ENTER YOUR EMAIL</label>
        <input type="email" name="email" id="id_email" ><br>
        <input type="submit" value="SEND OTP">
    </form>
</body>
</html>

proapp18/templates/customer_otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <label for="id_otp">Enter otp</label>
        <input type="number" name="otp_confirm" id="id_otp"><br>
        <input type="submit" value="confirm">
    </form>
</body>
</html>

proapp18/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    
   
    <title>welcome</title>
</head>
<body>

    {% include 'partials/_homeh.html' %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">IVAR Restaurant</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  
                  <li class="nav-item">
                    <a href="" class="nav-link">About us</a> </li>
            <li class="nav-item">
                <a href="{% url 'owner_app:owner_register' %} " class="nav-link">Add Restaurant</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="tel:6302141118">Contact us</a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'proapp18:register'%}" class="nav-link">Register</a></li>
                </ul>
                
              </div>
            </div>
          </nav>
        
        <main>
            <section>
                <img src="{% static 'images/foodhotel1.jpg'%}" class="rounded mx-auto d-block" alt="...">
            </section>
            <div class="container">
                <div class="row">
                  <div class="col-md-8">
                    </div>
                  <div class="col-md-4">
                    <h2>Restaurant News & Articles</h2>
                    <div class="article-snippet">
                      <h3>Article Title</h3>
                      <img src="article-image.jpg" alt="Article Image">
                      <p>Brief excerpt of the article...</p>
                      <a href="#">Read More</a>
                    </div>
                  </div>
                </div>
              </div>
        </main>
    </header>
</body>
</html>

proapp18/templates/items_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>items_user</title>
    <style>
         *{
            margin: 0%;
            padding: 0%;
            font-size: medium;
        }
        #item-div{
            border: 1px solid;
            margin: 2px ;
        }
        #cust-items{
            display:flex;
        }
    </style>
</head>
<body>
    {% include 'partials/_header.html' %}
    <div id="cust-items">
        {% if data %}
            {% for i in data %}
            <div id="item-div">
            <h4>{{i.item_name}}</h4>
            <img src="{{i.item_image.url}}" height="150px" width="150px">
            <h4>Name:{{i.item_name}}</h4>
            <h4>Price: {{i.item_price}}</h4>
            <h4>Hotel id: {{i.hotel_id}}</h4>
            <form action="{% url 'cart_app:cart_register'%}" method="post">
                {%csrf_token%}
                <input type="hidden" name="your_item_id" value="{{i.item_id}}">
                <input type="hidden" name="your_item_name" value="{{i.item_name}}">
                <input type="hidden" name="price" value="{{i.item_price}}">
                <input type="hidden" name="customer_id" value="{{user.id}}">
                <input type="hidden" name="hotel_id" value="{{i.hotel_id}}">
                <select name="quantity" id="">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <input type="submit" value="Add to cart">
            </form>
        </div>
            {% endfor %}
        {% endif %}
    </div>
    <a href="{% url 'proapp18:home'%}"><button>Hotel home</button></a>
    <footer>
        {% include 'partials/_footer.html' %}
        </footer>
</body>
</html>

proapp18/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login_page</title>
</head>
<body>
    {%if messages %}
    {% for i in messages %}
    <h5>{{i}}</h5>
    {% endfor %}
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{form}}
        </table>
        <input type="submit" value="login">
    </form>
    <h3>New User ? 
        <a href="{% url 'proapp18:register' %}"><button>Register</button></a></h>
        <a href="{% url 'proapp18:customer_forget' %}"><button>forget password</button></a>
</body>
</html>

proapp18/templates/otp_genrate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OTP_PAGE</title>
    
    <style>
        input{
            font-size: large;
            font-family:sans-serif ;
        }
        label{
            font-family: 'Times New Roman', Times, serif;
            font-size: large;
        }
    </style>
</head>
<body>
    <h1>OTP Confirm</h1>
    <form action="" method="post">
        {% csrf_token %}
        <label for="id_otp">Enter OTP</label>
        <input type="text" name="otp_confirm" id="id_otp"><br>
        <input type="submit" value="OTP SUBMIT">
    </form>
</body>
</html>

proapp18/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update profile</title>
    {% load static %}
    <style>
        body{
            display: flex;
            justify-content: center;
            align-items: center;

        }
        input{
            padding: 5px;
        box-shadow: 5px 3px 10px grey;
        font-size: 14px;
         font-weight: 600;
        width: 300px;

        }
        label {
            color: #1d1510;
            font-weight: bold;
            display: block;
            width: 150px;
            color: white;
}
form{
    line-height: 150%;
    padding-top: 6%;
    
}
        
    </style>
</head>
<body>
    <fieldset>
    <h2>Your Details are update and you have to use this  details only</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <br>
        <input type="submit" value="update" id="">
    </form>
</fieldset>
</body>
</html>

proapp18/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/register.css'%}">
    <title>Register_Page</title>
   
</head>
<body>
    <div>
        <header id="header">
            <img src="{%static '/images/burger.avif'%}" alt="">
            <img src="{%static '/images/ima.jpeg'%}" alt="" id="img-2">
        <li><a href="">AboutUs</a></li>
        <li><a href="">ContactUs</a></li>
        <li><a href="">Feedback</a></li>
        </header>
    </div>
    <div id="demo1">
        <div id="demo">
            <h1  id="h1-reg">Register Page</h1>
            <form action="" method="post">
                {% csrf_token %}
                    {{form.as_p}}
                <input type="submit" value="Register">
            </form>
                <h3>Already User ?  <button><a href="{% url 'proapp18:login' %}">Login</a></button></h3>
            
           <button><a href="{% url 'proapp18:start' %}">start</a></button> 
        </div>
        <aside><img src="{%static '/images/pexels.jpeg'%}" alt="" id="aside-img"></aside>
    </div>
</body>
</html>

proapp18/templates/start.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/start.css'%}">
    <title>welcome</title>
</head>
<body>
    <div id="start-div1"  class="">
    <h1>Welcome to Tindam Tirugudam</h1>
</header>
<br>
<main>
<h3>First, we eat. Then, we do everything else.</h3>
    <a href="{% url 'proapp18:register'%}"><button>Register</button></a>
    <p></p>
    <div id="main-img"><img id="img-1" src="{% static 'images/start.jpeg'%}" alt=""></div>
</main>
<h2>You are  already register go and login!!!</h2>
    <a href="{% url 'proapp18:login'%}"><button>Login</button></a>
</div>
</body>
</html>