crud_app/urls.py
from django.urls import path
from crud_app.views import catagory_view,display,updates,deletes,items_view,item_update,items_list,item_delete,details_view
app_name='crud_app'

urlpatterns=[
    #========FOR CATEGORY CREATED BY THE HOTEL_REGISTER======
    path(route='catagory/',view=catagory_view,name='catagory'),
    path(route='display/',view=display,name='display'),
    path(route='updates/<int:pk>/',view=updates,name='updates'),
    path(route='deletes/<int:pk>/',view=deletes,name='deletes'),
    #========FOR ITEMS CREATED ==============================
     path(route='items/',view=items_view,name='items'),
    path(route='items_list/',view=items_list,name='items_list'),
    path(route='item_update/<int:pk>/',view=item_update,name='item_update'),
    path(route='item_delete/<int:pk>/',view=item_delete,name='item_delete'),
    path(route='details_view/<pk>/',view=details_view,name='details_view'),
    # path(route='item_details_view/<pk>/',view=item_details_view,name='item_details_view'),
]

owner_app/urls.py
from django.urls import path
from owner_app.views import owner_register_view,otp_view,change_pass_view,sample_home_view,owner_login_view,sub_login_view,logout_view,items_display_view
app_name='owner_app'

urlpatterns=[
    path(route='owner_register/',view=owner_register_view,name='owner_register'),
    path(route='otp_view/<int:pk>/',view=otp_view,name='otp_view'),
    path(route='change_pass_view/<int:pk>/',view=change_pass_view,name='change_pass_view'),
    path(route='sample_home_view/',view=sample_home_view,name='sample_home_view'),
    path(route='owner_login_view/',view=owner_login_view,name='owner_login_view'),
    path(route='sub_login_view/',view=sub_login_view,name='sub_login_view'),
    path(route='logout/',view=logout_view,name='logout'),
    path(route='items_display_view/<int:pk>/',view=items_display_view,name='items_display_view'),


]

pro18/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from pro18.views import main_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('proapp18/',view=include('proapp18.urls'),name='proapp18'),
    path('crud_app/',view=include('crud_app.urls'),name='crud_app'),
    path('cart_app/',view=include('cart_app.urls'),name='cart_app'),
    path('buy_app/',view=include('buy_app.urls'),name='buy_app'),
    path('owner_app/',view=include('owner_app.urls'),name='owner_app'),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

crud_app/models.py
from django.db import models
class category_model(models.Model):
    category_id=models.AutoField(primary_key=True)
    hotel_id=models.IntegerField()
    category_name=models.CharField(max_length=30)
    category_desc=models.TextField()
    category_image=models.ImageField()
    def __str__(self):
        return self.category_name

    
class food_model(models.Model):
    category_id=models.ForeignKey(category_model,on_delete=models.CASCADE)
    hotel_id=models.IntegerField()
    item_id=models.AutoField(primary_key=True)
    item_name=models.CharField(max_length=30)
    item_price=models.FloatField()
    item_quantity=models.IntegerField(default=1)
    item_desc=models.TextField()
    item_image=models.ImageField()
    

crud_app/forms.py
from django import forms
from crud_app.models import category_model,food_model


class category_form(forms.ModelForm):
    class Meta:
        model=category_model
        exclude=['hotel_id']



class item_form(forms.ModelForm):
    class Meta:
        model=food_model
        exclude=['hotel_id','item_quantity']


    def __init__(self,*args,**kwargs):
        hotel=kwargs.pop('hotel',None)
        super(item_form,self).__init__(*args,**kwargs)
        self.fields['category_id']=forms.ModelChoiceField(queryset=category_model.objects.filter(hotel_id=hotel))

class items_update_form(forms.ModelForm):
    class Meta:
        model=food_model
        exclude=['category_id','hotel_id','item_quantity']   


    

crud_app/views.py
from django.shortcuts import render,redirect
from crud_app.models import category_model,food_model
from crud_app.forms import category_form,item_form,items_update_form
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
# Create your views here.


def catagory_view(request):
    form=category_form()
    if request.method=='POST' and request.FILES:
        form=category_form(request.POST,request.FILES)
        if form.is_valid():
            if request.user.is_staff:
                data=form.save(commit=False)
                data.hotel_id=request.user.id
                if data:
                    data.save()
                    messages.success(request,'category is created')
                    return redirect('/crud_app/display')
            else:
                messages.error(request,'You are not a owner')
    return render(request,'category.html',context={'form':form})
@login_required(login_url='/owner_app/owner_login_view/')
def display(request):
    res=category_model.objects.filter(hotel_id=request.user.id)
    return render(request,'display.html',context={'form':res})

@login_required(login_url='/owner_app/owner_login_view/')
def updates(request,pk):
    res=category_model.objects.get(category_id=pk)
    form=category_form(instance=res)
    if request.method=='POST' and request.FILES:
        form=category_form(request.POST,request.FILES,instance=res)
        if form.is_valid():
            if request.user.is_staff:
                form.save()
                messages.success(request,'category is updated')
                return redirect('/crud_app/display')
            else:
                messages.error(request,'You are not a owner')
    return render(request,'update.html',context={'form':form})

@login_required(login_url='/owner_app/owner_login_view/')
def deletes(request,pk):
    res=category_model.objects.get(category_id=pk)
    if request.method=='POST':
        if request.user.is_staff:
            res=category_model.objects.get(category_id=pk).delete()
            messages.success(request,'category is deleted')
            return redirect('/crud_app/display')
        else:
            messages.error(request,'You are not a owner')
    return render(request,'delete.html',context={'form':res})


#items for  category
@login_required(login_url='/owner_app/owner_login_view/')
def items_view(request):
    form=item_form(hotel=request.user.id)
    if request.method=='POST' and request.FILES:
        form=item_form(request.POST,request.FILES,hotel=request.user.id)
        if form.is_valid():
            if request.user.is_staff:
                data=form.save(commit=False)
                data.hotel_id=request.user.id
                if data:
                    data.save()
                    messages.success(request,'item is created')
                else:
                    messages.error(request,'You are not a owner')
                return redirect('/crud_app/items_list')
    return render(request,'items.html',context={'form':form})


@login_required(login_url='/owner_app/owner_login_view/')
def items_list(request):
    res=food_model.objects.filter(hotel_id=request.user.id)
    return render(request,'items_list.html',context={'form':res})

@login_required(login_url='/owner_app/owner_login_view/')
def item_update(request,pk):
    res=food_model.objects.get(item_id=pk)
    form=items_update_form(instance=res)
    if request.method=='POST' or request.FILES:
        form=items_update_form(request.POST,request.FILES,instance=res)
        if form.is_valid():
            if request.user.is_staff:
                form.save()
                messages.success(request,'item is updated')
            else:
                messages.error(request,'You are not a owner')
            return redirect('/crud_app/items_list')
    return render(request,'items_update.html',context={'form':form})
@login_required(login_url='/owner_app/owner_login_view/')
def item_delete(request,pk):
    res=food_model.objects.get(item_id=pk)
    if request.method=='POST':
        if request.user.is_staff:
            res=food_model.objects.get(item_id=pk).delete()
            messages.success(request,'item is deleted')
            return redirect('/crud_app/items_list')
        else:
            messages.error(request,'You are not a owner')

    return render(request,'items_delete.html',context={'form':res})

@login_required(login_url='/owner_app/owner_login_view/')
def details_view(request,pk):
    res=food_model.objects.filter(category_id=pk,hotel_id=request.user.id)
    return render(request=request,template_name='items_details.html',context={'res':res})

crud_app/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>create_page</title>
    <style>
        /* Apply a simple reset to remove default margins and padding */
 label, input, textarea {
  margin: 0;
  padding: 0;
}

/* Add some basic styling to the container divs */


/* Style the labels for better readability */
label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

/* Style the text input and textarea */
input[type="text"],
textarea {
  width: 100%;
  padding: 10px;
  margin-bottom: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

/* Style the file input */
input[type="file"] {
  margin-top: 5px;
}

/* Add some basic responsiveness for smaller screens */
@media screen and (max-width: 600px) {
  input[type="text"],
  textarea {
    width: calc(100% - 20px);
  }
}
form{
    width: 50%;
    padding: 10%;
}

    </style>
</head>
<body>
    {% include 'partials/_messages.html' %}
    {% include 'partials/_header_owner.html' %}
    
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="create" id="">
    </form>
    <br>
    <a href="{% url 'crud_app:display'%}"><button>Category_display</button></a>
    <a href="{% url 'crud_app:items'%}"><button>Items_create</button></a>
</body>
</html>

crud_app/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% include 'partials/_messages.html' %}
    <h2>Delete page</h2>
    <h4>Are you sure to delete the record id: {{form.category_id}}  catagory name :{{form.category_name}}</h4><br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" name="" id="" value="delete">
    </form>
    <div>
        <a href="{% url 'crud_app:display'%}"><button>back to display page</button></a>
        <a href="{% url 'crud_app:catagory'%}"><button>Category</button></a>
    </div>
</body>
</html>

crud_app/templates/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *{
            font-size: large;
            border: 1px solid black;
        }
    </style>
</head>
<body>
    {% if form %}
    <table border="2">
        <tr>
            <th>category_id</th>
            <th>category_name</th>
            <th>category_desc</th>
            <th>category_image</th>
            <th>update</th>
            <th>Delete</th>
        </tr>
        {% for i in form %}
        <tr>
           <td>{{i.category_id}}</td>
          <td>{{i.category_name}}</td>
            <td>{{i.category_desc}}</td>
            <td><img src="{{i.category_image.url}}" alt="...." height="150" width="150"></td>
            <td><a href="{% url 'crud_app:updates' pk=i.category_id %}"><button>update</button></a></td>
            <td><a href="{% url 'crud_app:deletes' pk=i.category_id %}"><button>delete</button></a></td>
             
        </tr>
        {% endfor %}
    </table>
    {% else %}
        <h2>Data not found</h2>
    {% endif %}
    <div style="text-align: center;">
     <a href="{% url 'crud_app:catagory'%}">  <input type="button"  value="category"></a> 
    </div>
    <a href="{% url 'owner_app:sample_home_view' %}"><button>
        Home
    </button></a>
</body>
</html>

crud_app/templates/items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <style>
        /* Default Styles */
body {
    font-family: 'Arial', sans-serif;
    background-color: #f8f8f8;
    color: #333;
    margin: 0;
    padding: 0;
}

.container {
    max-width: 600px;
    margin: 20px auto;
    padding: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    display: flex;
    justify-content: center;
    background-color: #fff;
    font-size: x-large;
    color: #333;
    fill-opacity: 5px;
}

label {
    display: block;
    margin-bottom: 8px;
}

input[type="text"],
textarea,
input[type="number"],
select,
input[type="file"] {
    width: 100%;
    padding: 8px;
    margin-bottom: 16px;
    box-sizing: border-box;
}

/* Light Theme */
.light-theme {
    
}

/* Dark Theme */
.dark-theme {
    background-color: #333;
    color: #fff;
}

/* Colorful Theme */
.colorful-theme {
    background-color: #ffc107;
    color: #333;
}

/* Responsive Design */
@media only screen and (max-width: 600px) {
    .container {
        max-width: 100%;
        padding: 10px;
    }
}

/* Additional Styling for File Input */
input[type="file"] {
    border: 1px solid #ccc;
    background-color: #f1f1f1;
}

/* Hover Effect for File Input */
input[type="file"]:hover {
    background-color: #e0e0e0;
}

    </style>
</head>
<body > <div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="add_item">
    </form>
    
</div>
<a href="{% url 'crud_app:items_list'%}"><button>Items_display</button></a>
    <a href="{% url 'crud_app:catagory'%}"><button>Category</button></a>
</body>
</html>

crud_app/templates/items_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item_deletepage</title>
</head>
<body>
    {% include 'partials/_messages.html' %}
    <h2>Here you can delete the data</h2>
    <h1>The product Id is:{{form.item_id}} and the product name is :{{form.item_name}}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" name="" id="" value="delete">
    </form>
    <a href="{%url 'crud_app:items_list' %}"><button>Back to list</button></a>
    <a href="{%url 'crud_app:items' %}"><button>Back to items</button></a>
</body>
</html>

crud_app/templates/items_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *{
            margin: 0;
            padding: 0;

        }
        #items-dis{

            display: flex;
            justify-content: space-around;
            border: 1px solid;
            font-size: x-large;
        }
        #item{
            border: 1px solid;
        }
        nav{
            padding: 10px;
            font-size: x-large;
        }
    </style>
</head>
<body>
    <header>
        <nav>
            <ul style="list-style-type: none; display: flex; border: 1px solid; justify-content: space-evenly;">
                <li>Home</li>
                <li>ContactUs</li>
            </ul>
        </nav>
    </header>
    <div id="items-dis">
    {% if res%}
        
        {% for i in res %}
        <div id="item">
        <h4>{{i.item_name}}</h4>
        <h4>{{i.item_price}}</h4>
        <img src="{{i.item_image.url}}" alt="" height="100px" width="100px">
        <h4>{{i.item_desc}}</h4>
        </div>
        {% endfor %}
        
    {% endif %}
</div>
<a href="{% url 'crud_app:items' %}"><button>
    items create
</button></a>
</body>
</html>

crud_app/templates/items_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        
    </style>
</head>
<body>
    {%if messages %}
        {% for i in messages %}
        <h5>{{i}}</h5>
        {% endfor %}
    {% endif %}
    {% if form %}
    <table  border="2">
        <tr>
            <th>category_id</th>
            <th>Item_id</th>
            <th>Item_name</th>
            <th>Item_Price</th>
            <th>Item_quantity</th>
            <th>Item_desc</th>
            <th>image</th>
            <th>update</th>
            <th>Delete</th>
        </tr>
        {% for i in form %}
        <tr>
            <td>{{i.category_id_id}}</td>
            <td>{{i.item_id}}</td>
            <td>{{i.item_name}}</td>
            <td>{{i.item_price}}</td>
            <td>{{i.item_quantity}}</td>
            <td>{{i.item_desc}}</td>
            <td><img src="{{i.item_image.url}}" alt="...." height="50" width="50"></td>
             <td><a href="{% url 'crud_app:item_update' pk=i.item_id %}"><button>update</button></a></td>
            <td><a href="{% url 'crud_app:item_delete' pk=i.item_id %}"><button>delete</button></a></td> 
        </tr>
        {% endfor %}
    </table>
    {% else %}
    {% endif %}
    <a href="{% url 'owner_app:sample_home_view' %}"><button>
        Home
    </button></a>
</body>
</html>

crud_app/templates/items_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% include 'partials/_messages.html' %}
    <form action="" method="post" enctype="multipart/form-data" >
        <table border="2">
        {% csrf_token %}
        {{form}}
    </table>
        <input type="submit" value="update">
    </form>
</body>
</html>

crud_app/templates/non_veg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>pick your favourate non-veg items</h1>
    
</body>
</html>

crud_app/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>update_page</title>
    <style>
       /* Default Styles */
body {
    font-family: 'Arial', sans-serif;
    background-color: #f8f8f8;
    color: #333;
    margin: 0;
    padding: 0;
}

.container {
    max-width: 800px;
    margin: 20px auto;
    padding: 20px;
    background-color: #fff;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

label {
    display: block;
    margin-bottom: 8px;font-size: xx-large;

}

input[type="text"],
textarea,
input[type="file"] {
    width: 100%;
    padding: 8px;
    margin-bottom: 16px;
    box-sizing: border-box;
    font-size: large;
}

/* Light Theme */
.light-theme {
    background-color: #fff;
    color: #333;
    
}

/* Dark Theme */
.dark-theme {
    background-color: #333;
    color: #fff;
}


/* Responsive Design */
@media only screen and (max-width: 600px) {
    .container {
        max-width: 100%;
        padding: 10px;
    }
}

/* Additional Styling for File Input */
input[type="file"] {
    border: 1px solid #ccc;
    background-color: #f1f1f1;
}

/* Hover Effect for File Input */
input[type="file"]:hover {
    background-color: #e0e0e0;
}

    </style>
</head>
<body> 
    <div class="container">
    {% include 'partials/_messages.html' %}
    <form action="" method="post" enctype="multipart/form-data" class="colorful-theme">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="update" id="" class="dark-theme">
    </form>
  </div>
</body>
</html>